# SPDX-FileCopyrightText: 2024 SUSE LLC
#
# SPDX-License-Identifier: BSD3

name: Build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  release:
    types:
      - published

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        mkdir -p ./bin
        go build -o ./bin/ -v ./...

    - name: Test
      run: go test -v ./...

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: ./bin/*
